apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
  labels:
    run: nginx
  creationTimestamp: null
spec:
  containers:
  - image: nginx:1.29.0
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
